In [2]:
a=5

In [3]:
print(a)

5


demo

#jupyter


# notebook


In [99]:
str='sddsddsds yyuy jjk'

In [51]:
str[slice(1,4,2)]

'ds'

In [52]:
str[:]

'sddsddsds'

In [34]:
str.index('dds')

1

In [35]:
str[5]

'd'

In [36]:
str[-3]

's'

In [2]:
print(str)

sds


In [4]:
ls=[1,'d',3.9]

In [53]:
ls[:2]

[1, 'd']

In [54]:
ls[1:2]

['d']

In [55]:
ls[1:3:1]

['d', 3.9]

In [37]:
ls.index('d')

1

In [38]:
ls[2]

3.9

In [39]:
ls[-3]

1

In [5]:
print(ls)

[1, 'd', 3.9]


In [10]:
from array import *
arr=array('i',[1,2,2,4])

In [69]:
print(arr+ 3)

TypeError: can only append array (not "int") to array

In [59]:
arr[1:-1]

array('i', [2, 2])

In [40]:
arr[2]

2

In [41]:
arr[-2]

2

In [7]:
print(arr)

array('i', [1, 2, 3, 4])


In [11]:
for x in arr: print(x)

1
2
2
4


In [14]:
tu=(1,9,'4f')

In [61]:
tu[1:3]

(9, '4f')

In [42]:
tu.index(9)

1

In [15]:
print(tu)

(1, 9, '4f')


In [16]:
tup=1,2,'rr'
print(tup)

(1, 2, 'rr')


In [82]:
tup+=('r','t')
print(tup)

(1, 2, 'rr', 'r', 't', 'r', 't')


In [43]:
tup[2]

'rr'

In [17]:
dicts={1:"dghdg",'sec':7}


In [56]:
dict[:2]

TypeError: 'type' object is not subscriptable

In [46]:
dicts['sec']

7

In [18]:
dicts

{1: 'dghdg', 'sec': 7}

In [20]:
dictss=dict([(1,'rus'),('se',3)])
dictss

{1: 'rus', 'se': 3}

In [45]:
dictss[1]

'rus'

In [21]:
sete={56567,"fghsf"}

In [83]:
sete,23

({56567, 'fghsf'}, 23)

In [22]:
sete


{56567, 'fghsf'}

In [23]:
seet=set('example')

In [24]:
seet


{'a', 'e', 'l', 'm', 'p', 'x'}

In [25]:
re=range(1,5,1)

In [26]:
range


range

In [27]:
re

range(1, 5)

In [28]:
print(re)

range(1, 5)


In [30]:
for x in re :print(x)

1
2
3
4


In [47]:
re[2]

3

In [48]:
re.index[2]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [49]:
re.index(2)

1

In [50]:
re.index(66)

ValueError: 66 is not in range

In [62]:
re[1:-1]

range(2, 4)

In [66]:
print(re[1:2])

range(2, 3)


In [70]:
str


'sddsddsds'

In [71]:
str+'eeee'

'sddsddsdseeee'

In [72]:
str

'sddsddsds'

In [73]:
ls


[1, 'd', 3.9]

In [76]:
ls+'py'

TypeError: can only concatenate list (not "str") to list

In [75]:
py=['2','rrr']

In [77]:
ls+'py'

TypeError: can only concatenate list (not "str") to list

In [79]:
ls+['jk']


[1, 'd', 3.9, 'jk']

In [80]:
ls

[1, 'd', 3.9]

In [84]:
str*10

'sddsddsdssddsddsdssddsddsdssddsddsdssddsddsdssddsddsdssddsddsdssddsddsdssddsddsdssddsddsds'

In [85]:
str

'sddsddsds'

In [86]:
ls*2

[1, 'd', 3.9, 1, 'd', 3.9]

In [89]:
ls[1]*=2
ls

[1, 'dd', 15.6]

In [92]:
tu[2:3]
tu[2:3]*2

('4f', '4f')

In [93]:
arr*2

array('i', [1, 2, 2, 4, 1, 2, 2, 4])

In [94]:
re*2

TypeError: unsupported operand type(s) for *: 'range' and 'int'

In [95]:
str

'sddsddsds'

In [96]:
print(str)

sddsddsds


In [101]:
print(str.swapcase())

SDDSDDSDS YYUY JJK


In [109]:
str.replace('yyuy','ds')

'sddsddsds ds jjk'

In [111]:
str.isalnum()

False

In [112]:
name1='git'
name2='hun'
name3='hjhjhjh'

In [114]:
 name='{}{}.{}'.format(name1,name2,name3)
name

'githun.hjhjhjh'

In [119]:
print (dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [120]:
print(ls)

[1, 'dd', 15.6]


In [121]:
ls.reverse()

In [122]:
print(ls)

[15.6, 'dd', 1]


In [128]:
print("list {} ,\ array {}".format(len(ls),len(arr)))

list 3 ,\ array 4


In [129]:
ls.clear


<function list.clear()>

In [130]:
ls.clear()

In [131]:
ls

[]

In [132]:
ls=[1,2,3,4]

In [134]:
print(sete)
sete.add(2222)
print(sete)

{'fghsf', 222, 56567}
{'fghsf', 2222, 222, 56567}


In [135]:
ls.append([22,1])

In [136]:
ls

[1, 2, 3, 4, [22, 1]]

In [137]:
arr.append(2222)
arr

array('i', [1, 2, 2, 4, 2222])

In [139]:
sete.update([2,222222])

In [140]:
print(sete)

{1, 2, 3, 4, 'fghsf', 2222, 222222, 56567, 222}


In [141]:
dictss[32]='jfhjdhjkf'
print(dictss)

{1: 'rus', 'se': 3, 32: 'jfhjdhjkf'}


In [153]:
dictss.update(eightfffff = 5)
print(dictss)

{1: 'rus', 'se': 3, 32: 'jfhjdhjkf', 'five': 5, 'f2': 5, 'eightfffff': 5}


In [154]:
len(dictss)

6

In [155]:
list(dictss)

[1, 'se', 32, 'five', 'f2', 'eightfffff']

In [163]:
dictss.get('five')

5

In [165]:
dictss.keys()

dict_keys([1, 'se', 32, 'five', 'f2', 'eightfffff'])

In [167]:
dictss.items()

dict_items([(1, 'rus'), ('se', 3), (32, 'jfhjdhjkf'), ('five', 5), ('f2', 5), ('eightfffff', 5)])

In [168]:
arr.insert(0,999)
ls.insert(0,999)

In [169]:
print(arr)
print(ls)

array('i', [999, 1, 2, 2, 4, 2222])
[999, 1, 2, 3, 4, [22, 1]]


In [172]:
print(arr)
arr.pop()


array('i', [999, 1, 2, 2])


2

In [173]:
ls.pop()

[22, 1]

In [174]:
ls.append(323)

In [175]:
ls.pop(0)

999

In [176]:
ls

[1, 2, 3, 4, 323]

In [177]:
print(dictss)
dictss.pop('five')

{1: 'rus', 'se': 3, 32: 'jfhjdhjkf', 'five': 5, 'f2': 5, 'eightfffff': 5}


5

In [189]:
sete.pop()

4

In [186]:
sete(2)

TypeError: 'set' object is not callable

In [190]:
arr.remove(2)
print(arr)

ValueError: array.remove(x): x not in array

In [191]:
ls.remove(2)

In [192]:
print(ls)

[1, 3, 4, 323]


In [194]:
sete.discard(8989)

In [195]:
del ls

In [197]:
print(ls)

NameError: name 'ls' is not defined

In [199]:
ls=[1,2,2,2,3,3,4]

In [200]:
del ls[2]

In [201]:
print(ls)

[1, 2, 2, 3, 3, 4]


In [202]:
arr.extend((9898,10009))

In [203]:
arr


array('i', [999, 1, 9898, 10009])

In [204]:
arr.extend([2,22])

In [205]:
arr

array('i', [999, 1, 9898, 10009, 2, 22])

In [206]:
arr.extend(['sam'])

TypeError: an integer is required (got type str)

In [207]:
print(list)

<class 'list'>


In [208]:
print(ls)

[1, 2, 2, 3, 3, 4]


In [209]:
arr.fromlist(ls)

In [210]:
print(ls)

[1, 2, 2, 3, 3, 4]


In [211]:
arr

array('i', [999, 1, 9898, 10009, 2, 22, 1, 2, 2, 3, 3, 4])

In [212]:
arr.tolist()

[999, 1, 9898, 10009, 2, 22, 1, 2, 2, 3, 3, 4]

In [213]:
arr

array('i', [999, 1, 9898, 10009, 2, 22, 1, 2, 2, 3, 3, 4])

In [214]:
print(arr)

array('i', [999, 1, 9898, 10009, 2, 22, 1, 2, 2, 3, 3, 4])


In [215]:
sete

{222, 2222, 222222, 56567, 'fghsf'}

In [219]:
b={99,990,222}

In [217]:
sete.union(b)

{222, 2222, 222222, 56567, 99, 990, 'fghsf'}

In [220]:
sete.intersection(b)

{222}

In [221]:
print(sete&b)

{222}


In [222]:
print(sete|b)

{99, 990, 222222, 'fghsf', 56567, 222, 2222}


In [4]:
import numpy as np


In [3]:
ls=[1,2,3,4,5]

In [8]:
ar=np.array(ls)

In [226]:
sr

NameError: name 'sr' is not defined

In [227]:
ar

array([1, 2, 2, 3, 3, 4])

In [9]:
print(ar)

[1 2 3 4 5]


In [5]:
ar1=np.array(ls,dtype= str )

In [10]:
print(ar1)

['1' '2' '3' '4' '5']


In [11]:
ar.type()

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [12]:
type(ar1)

numpy.ndarray

In [13]:
len(ar1)

5

In [14]:
ar1.ndim

1

In [15]:
ar.shape

(5,)

In [16]:
ar=ar.reshape(5,1)

In [17]:
ar.shape

(5, 1)

In [18]:
ar

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
ar1=ar1.reshape(1,-1)

In [26]:
ar1

array([['1', '2', '3', '4', '5']], dtype='<U1')

In [27]:
ar1.shape

(1, 5)

In [28]:
ls1=[1,2]
ls2=[3,4]

In [31]:
ar2=np.array([ls1,ls2])

In [32]:
ar2

array([[1, 2],
       [3, 4]])

In [33]:
ar2.shape

(2, 2)

In [34]:
ar2.shape=(1,4)

In [35]:
ar2

array([[1, 2, 3, 4]])

In [36]:
r=range(20)

In [37]:
r

range(0, 20)

In [38]:
ar3=np.arange(9)

In [39]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
ar3.shape

(9,)

In [42]:
ar3.ndim

1

In [46]:
c=ar3.reshape(9,1,1)

In [47]:
c

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]]])

In [48]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[1,1],[1,1]],dtype=np.float64)

In [49]:
x
y

array([[1., 1.],
       [1., 1.]])

In [50]:
x



array([[1., 2.],
       [3., 4.]])

In [51]:
y

array([[1., 1.],
       [1., 1.]])

In [52]:
x-y

array([[0., 1.],
       [2., 3.]])

In [53]:
x add y

SyntaxError: invalid syntax (Temp/ipykernel_12244/1316669124.py, line 1)

In [54]:
x sum y

SyntaxError: invalid syntax (Temp/ipykernel_12244/3021196491.py, line 1)

In [55]:
sum(x,y)

array([[5., 7.],
       [5., 7.]])

In [57]:
np.add(x,y)

array([[2., 3.],
       [4., 5.]])

In [58]:
np.dot(x,y)

array([[3., 3.],
       [7., 7.]])

In [61]:
x.dot(y)

array([[3., 3.],
       [7., 7.]])

In [62]:
np.sum(y)

4.0

In [63]:
np.sum(y,0)

array([2., 2.])

In [67]:
tup=(1,2,3,'4')

In [68]:
max(tup)

TypeError: '>' not supported between instances of 'str' and 'int'

In [66]:
type(tup)

tuple